apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: generic-pwd
  namespace: monitoring
spec:
  length: 48
  digits: 5
  symbols: 5
  symbolCharacters: "-_"
  noUpper: false
  allowRepeat: true
