---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: homelab-media
  namespace: flux-system
spec:
  interval: 5m
  url: ssh://git@ssh.git.fung.house/kingston/homelab-media.git
  ref:
    # can be a tag or branch
    #tag: v0.0.1
    branch: dev
  #
  secretRef:
    name: gitea-bot-homelab-ro-ssh
  recurseSubmodules: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: mod-homelab-media
  namespace: flux-system
spec:
  force: true
  interval: 10m0s
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-media
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
      - kind: ConfigMap
        name: cluster-settings-user
      - kind: Secret
        name: cluster-secrets-email
      - kind: Secret
        name: cluster-secrets-user
      - kind: Secret
        name: cluster-secrets-hw
