apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:MQw1VOYAIV4=,iv:+KC/IoTCvRskdofZwoBbfxROKugxvxmH+SMEjAdFVWk=,tag:ceq0D+H1vvX//m2kgYW6KA==,type:str]
    admin-user: ENC[AES256_GCM,data:a6K3EOk=,iv:70jaHuY6BcJfMxI2atYAiRU/Ch+FBgaSGa3Q2pz4EIs=,tag:F0h/QN+HAsYM6NQRm9RDQA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qh3gh9vltq82hgjxdtga37svmdvzj2zgdxzt0zzsh4rndmtlkujsmrw26m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBWk1pcXhEaE84eElnVHox
            ZlR0QlRzZTJ4TEJlUGVNVUdqWGJ2blQxeEJBCksrWXVOQ1dRazFQNnFnTHBMeW5t
            bDQ5OEg0NkJwVjNqbXpuKytUOUgvdGcKLS0tIGVvSHRPU1lvaXVGVStyWUttU1Q0
            ZldseGhqSVovUlphQ1dBaWkwaXA0d0EKCRkuQEFfU06O1YEVkPiPrrQ+01vT+/Nq
            qIJI2KsBylGlLoilCcPFDxuuU7cwBFED/kWiBqRnC3d8o8w0qFAA5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-18T00:58:57Z"
    mac: ENC[AES256_GCM,data:YRCbr6VceTpf/rszU7GTMOU4YNyoUkT4Sxb5wSJoIsoO6z9G5Pk5nJprwvl3eX4XFv+JKogGk94icGcYHETvydNVkeimwpfWl5VLqqDKeWQKcWz0h//fW7i0uQ/Fm+rN1B0oj0s8iBva37h8KMcfFotPaXau9IQTGjMdsOtStnQ=,iv:8yP+sZ7vdkQBbUrmtt3ByBLrukdlqyRZCy6AMy/vZ08=,tag:k52dgOtlETHi6m6AjPZ3oQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
