apiVersion: v1
kind: Secret
metadata:
    name: gitea-webhook-token-secret
    namespace: flux-system
stringData:
    #ENC[AES256_GCM,data:YDIzuopZrtxF8DB0lk5/vlLtjyc/5MebzOM2173n1Fhceroyyw5aO+f8q2fkdXet+l/uq2ndGQjwxk4mivymCP5dJtpJjtnmF3VHy81hET1N4WVztg1WKWJKkdU=,iv:CdMxGEeCCTX6YkrHlUIO/nioVcLqpemAD7ElHv4XMgQ=,tag:RLsjBFpG14DvHPhZPPW2pg==,type:comment]
    token: ENC[AES256_GCM,data:2zL6fAvlHzY9RGZI2bW2OYvI0MSlnv0pCOHaX3CGJlkRLrZtDEMh7Q==,iv:E20MzkhUfWViT2CabYCFXx44Q372ScwpnEqdJkDTQmc=,tag:gZVQJdMxmUBB6P4JQzCEIA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qh3gh9vltq82hgjxdtga37svmdvzj2zgdxzt0zzsh4rndmtlkujsmrw26m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTk5Kd3M4dzY1R0ZtVEhS
            a1NZQUQxMXlpMnhGMklvZjIzdHovczdLWVJRCm1IZWVxUTFrOTk0clRhRkd6QVBD
            NCtlaVllL3hVbDhqWmExbDFHME9SUlUKLS0tIGhwTW9mNUdxcGRVU3JQbXFna3V5
            WWlrRnp1Z2pad2RQK25zV0tJNmVNblEK8MLexrzVXq4BlAjz7ceG2J/AHEGADhjs
            kBZHSTA88J9vyCxUxV4NlIYgRuFd12g2O96Sd6qi18hJkrXRuAPJlQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-03T06:15:43Z"
    mac: ENC[AES256_GCM,data:PpE6ZBlZqvbkDLqoi2zv4X9HTFuKSXp1CXrIEhf1h+pBFfJMpth5gfqfV6rm8RhFfE1BCHexq+iamLgZUCqxNnNwfSXHQ1yEz8sWj77SJnBmpuha9D/DEmEI/zFh8S1X973IZN6Lt+xXIDTupmTdNO/L7Y65KcG7dmH3D4YeJdY=,iv:EpLA7zEHEALisBKGDFNa6IoHMBZmg1OlNuRphPO7iyQ=,tag:OAYyA7jfN19qTs77RxniPg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
