apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Bxezu1fOGyjHMCd9q0f52rT0X0z67BBo,iv:4LzamBo1oHxRiMhxx8TTwtZqeSvTwkxXav4hIuwGLb0=,tag:es8la7MTiFYnBnzSSroZuw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qh3gh9vltq82hgjxdtga37svmdvzj2zgdxzt0zzsh4rndmtlkujsmrw26m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQQjVJVEI3bHIvMy9YcGJF
            MFhLSEVGTTRKekdxUThqQkwrTmR3emNLWkNZCmQ4dEQ0dUxKSWdkdkxuaTMzaW13
            TldzY0gxcU50WnVia0VCb1Z4aEhEL1EKLS0tIHl0QmZGRGg4QWJMQjB2THVDdDJP
            TExESWs1ZC94YjU0UVFXWS9tL2daWlkKN11hBqVUhvovNuyAUpjHohzj5iFakFjI
            1gW2Z38Pkf8wV21wLx3L3RXspYb2i7o2hsSHt7DvczNAivmZgIOTDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-15T01:07:39Z"
    mac: ENC[AES256_GCM,data:/Ptw8SjZdRXPqDqZfPJl7/qY40Fd5Mdv9SOAEFIYqVD5+Q82nm7NH26LQqbqeBK2wggogZQzq+ai6pKnnXycVlKmTwHMrmw2B7So61tRhbfT9Rpk0hAwPwvLVYgSQAhZMvKVfK1lNOLZwdHowkOIL1kpR4YqMGO2P+Hqibzs7DY=,iv:B3SEYGfbxzvuqTDCRMayEaVRmRvuXbkJPGICX2ygEBo=,tag:/LAwJ7ozzjPzCxIzng/RUA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
