apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:VTOtjqoGpUo3fvLFyAdG95GXJ+yu3vkS1aN5/76QAlRdIdk1V9umsA==,iv:sE787BHCkZtaTZTv+ciZ88t8QCToHSNpgl8tNkkIsWs=,tag:An6y9HxgpGmcYOsrzgjUog==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qh3gh9vltq82hgjxdtga37svmdvzj2zgdxzt0zzsh4rndmtlkujsmrw26m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKSXUxUXNrQmxndFBXNmw2
            TWxQY3h2c25ybVV1SXZGeEE4MWJjb0pDNEE0CmRvQXZvck5yd0dFUDBmWTNjbkpo
            WUxCVEcvMVZhUmsyS0NUdmFOaERBL2cKLS0tIGVkTnpONzFmL0ZtYkh1S0hod1Ux
            RzhXZEc5QU5uc3dPa3IvSmQvemdodmsKsDdwBBdgZ7cu/bPblC/mpYpH4H3YB3co
            Z2Ozn5QTPER6wOrsQ8pMzqQb2wFzFm0gUBz6ZKNAEj70UbqV6zNSUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-15T01:07:37Z"
    mac: ENC[AES256_GCM,data:moPonLFsyD5zH4ym4E2AcnvPcOqeTo8jh75NEh2aZ9LPj0qUemdcG/+mzo/NPm00zy6/nByPokzSvh0LS6SOMITpLYdD/52ceGNKycIAeNurk+QOclfP/MbCcy3U92nXwNcaW/GSjvMDkohTbc2GrO/LLUiQrniDRImXyLqp4fg=,iv:sTiDt4wDO48SmwoMOonXyHyn1lEN3gcVb5eN6AZHhmU=,tag:+l25xxlcMayKC81jnTtFYA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
