---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-gatus-ep
  namespace: monitoring
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: prometheus
        group: monitoring
        url: https://prometheus.${SECRET_DOMAIN}
        interval: 1m
        client:
          dns-resolver: tcp://1.1.1.1:53
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: ntfy
        ui:
          hide-url: true
          hide-hostname: true
