apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:BVEAOme6hO/EemmF,iv:JHLqRSrsQST3RoQmDMHGrCIhi0J2x0qU26FQKwp/Jf8=,tag:UcdaVhOb733p7+EbGxvfWg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qh3gh9vltq82hgjxdtga37svmdvzj2zgdxzt0zzsh4rndmtlkujsmrw26m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIOWxLOStlWmRYaStUZjhT
            QXZTNHVzRVFObm5zbFRqNnM0MlBXZUV6K3dRCmQwbnhzQ3QxRlBKemxMUHZQbndY
            WmJVMXBrZWhZQndGeXE1N3cvMDUxYlkKLS0tIEF4VDBuTlhhaXhjcURndkhrc05P
            SW4wZlNpYjVBNCtTbXBONmpxL254MXcKY6jvMj9iUfrUKIxIaaPoI/4r9/ExShpa
            f5UJNXWxWG3oHAfU2reUS6E4BTOzZ5oSvAN1X/ikumFRWzrXIlRxtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-15T00:29:20Z"
    mac: ENC[AES256_GCM,data:WzyuE1V3l0ma1wdCUCVZtLAcevKQxC8omtayB7vbVMwp2SiXLEuYlPGfawPfQ4gB691joBK2JVrKgxR8pLPvNE3Gpstl/Kp8C10HNnzePLTrlEPRJFowlhzFg4E6OrZp4sb28Bu0orPJfrFsXkJISCvpHnEkPJIycpN6rWc7BGo=,iv:qxcFmvsEvxg/+C4bMuIrGiaPZCXv6hVx1t7hr6FEYSI=,tag:ZkqtFTQom6KUbrY/qiatHw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
