apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:tYwo2I5rNvTBxZr9SsvaLE779Fzauw==,iv:VSgF/ycyS4YsafuGQRojokoO+wMUBprT//8ijqnXo6Y=,tag:6yOpTr5C7p1HlPv8s90YNw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:L5LzEwZxYxnZPPL9mZOkCFSxc0vGT2C17bHqJeJB7AUia+Ng,iv:1STQpDxyqCAVkvmxw9iYw6iAci4HoYxz5/YnMfNc+Jw=,tag:zRNGG6nXlJLAv7XzVkLB9w==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:DXCgSAMtMWr5pg==,iv:IZeV8nGsg3++eUVae3+DW+uokD3IphruCQdrhtpsvzY=,tag:QHQwAJiei4je61ggBRxODg==,type:str]
    #ENC[AES256_GCM,data:VKzTnQ1/hCwMg87D82+sQQ5ePEGQCelBkW8MDYZvFLTBZglIz54hDGqkgmVcpCa5QxdB5MYcl6NdhDPQfjJQ,iv:C0schqJnQM3Y9aR6CFskUsvnAHKb6Iu7LxIAQteoJpY=,tag:da+kKMQ53nwhc4NW1qwY/A==,type:comment]
    SECRET_RESTIC_REPOSITORY_S3: ENC[AES256_GCM,data:UG+XXZvm/DzETOUcaje9uA==,iv:aHBH3Jt4wxkahMq6CyBwIZygqqzwHVmbDK3aMeb10j0=,tag:iBXc/8nHHm5nMvRzAljXEg==,type:str]
    SECRET_RESTIC_FAMILY_PV_REPO: ENC[AES256_GCM,data:oBCHgw7+bIqw6IE8qBF/a+hJMcyoZFWRlOfNPOvftEffqh8N,iv:itTuDw/pxvEAQuYo3360uD6A8rioUoa4Cj2Sbi79rq8=,tag:HUAC2CIpRlpRQfFIxqe9DQ==,type:str]
    SECRET_RESTIC_FAMILY_MEDIA_REPO: ENC[AES256_GCM,data:sXY44FkppRWOnh5wCwgi5AAVZNiWqSU1,iv:G3RDswjmCuVaqDIQQKHcrtEw6D0pdxdB4zmY7HEV5hE=,tag:S7lR5pM677Dunft+/nBHmg==,type:str]
    SECRET_RESTIC_BANG_PV_REPO: ENC[AES256_GCM,data:q3l0SHZh3JSIvyZ3lrri1Kd4NJ7GKKwX,iv:nE+2Rm9CLBW8TBJMN3mkWOX4lwKkdFjgnC+OfCVnd4E=,tag:ESi4XDTb+3SV4Onr9z5H9A==,type:str]
    SECRET_RESTIC_BANG_MEDIA_REPO: ENC[AES256_GCM,data:KgJJ8Sfra/ImrklZ5eVg3876I+QoBKfq,iv:+QXvlbryFsiSpEMQ/t/HgbG2ev0bPhwA4dttMqCfv8U=,tag:PzpapARDUsdvrFuwAj7vkA==,type:str]
    SECRET_RESTIC_DEV_PV_REPO: ENC[AES256_GCM,data:rwHepUoV+4rAVZjhdyy4D5ZYxG8Z/kkQ,iv:wdZb7tSfYRb87PtQHkHtWeFoWMjSAm+DrW0fWf9XMwo=,tag:g4mdeHtM9MDmlBpl/PlhAg==,type:str]
    SECRET_RESTIC_DEV_MEDIA_REPO: ENC[AES256_GCM,data:dIxpWV7lfhb6nxldsa04x3bUmHcAaaBW,iv:IRmPEuMw783Oc8v/O/Dq3Hx09ITbiaonRGyGGydkw0Y=,tag:2IvWO0JHfRX1WAXcnQ7ecw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qh3gh9vltq82hgjxdtga37svmdvzj2zgdxzt0zzsh4rndmtlkujsmrw26m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0SmNpazBkV0Vvc2ZRa0I4
            bkl5bHR5d05MOFdkaGtyQWlkNk5Oczd3N0ZFClBsOSsyZE8waE9UcExIOVVVYTYz
            UGpjYmhNbWVCTGlhangvZG5ueEovT2MKLS0tIENSbUtLRnBmTEs2UmN4S2RaV0Zm
            NlNQMjBwQk5OdnVKRXFHK1JNY2dEZkUKaS6HdWz8WOUzzdzULXO9n4wnPGqm4PEO
            nUgaS96glV8vEE0WIXRENSNhDd89MfeZ7pHCfHyMCsyrHXArNy76+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-31T02:15:38Z"
    mac: ENC[AES256_GCM,data:yWFallAE+TbPMEInkQvvVPypkzR17Raj5a+C7QWOYhR9u/mmLFZtsThypWfYcFXVzCllovVnK3zcVYJvrZxlZPvZ51NjX9eED4xHprwtPwmpUhOtZHq+m4hVmvae2x56XGyEiOwBXKEhSbdQqwXOrEqIQER5flh0BuFOE2PMQas=,iv:TgC0BG/15sxL0KPjTgLnZlKqdqtntvmiLasY1LKgGUg=,tag:XUbaZd6Yc7Ju5RNPgwhD2g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
