apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:66RMqhbpomsUZ3zsMjZbtd1b9196j5GNYkHD8wS+7wk3V33M,iv:S5CWxKwGXBdWC7qv2baoXULSxev/eQuEoIVJLeruXno=,tag:JHppURAX01bIJp7CzxVDFQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:piRXkfmZvHoHiQ==,iv:Qg90WsFs9Cpv7NIKds9uiYwN4w3izvqZlQIm0YxrI4M=,tag:YWJzr7hTxrfvvNNazRKJMA==,type:str]
    SECRET_GRAFANA_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:HX33mY7ZA0rFYjU9,iv:0CZMe2fyV/pEaBgZSFfe0+pdgZrOWHA8d8OublImHBA=,tag:JMTS2zyqvW9xzvs9F3cZwQ==,type:str]
    SECRET_GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:UHjIgV8X2MphZ4dA,iv:1p7/1VGBd3d/uucjnjxvh4V4UJphVvIrRu1jKTOO9RQ=,tag:YagTrFOXw/QuqZvSucIP3Q==,type:str]
    SECRET_VIKUNJA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:BixrwmL+cM4Tz3Rqza8YvJgInXW6fOYtMY7eq+6v0Rd5Un+l,iv:y+4u5ABLg5QUeGot5qtzTRIMmNG3CiAWlEHm9bfZomQ=,tag:kAaURqlAQuTUvt5awPXREA==,type:str]
    SECRET_GITEA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:6NsLSlLeViHbRDM3vu0cnMTpH7ZJTijzaFDi2im238ynk1J2KaeHXZHpSiL5sh3c,iv:4oh05HFvbH73a8eTOw5opw7z7eMJkDWWiSr+mrPWo18=,tag:+JOty6pCPGCSYLnAqng0Qg==,type:str]
    SECRET_VAULT_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:Qh4NFy6fvF80aPCtQ408rCFj6QaCF5rm2sU7VnYK5TWOoi7J,iv:LOwAkuTVhn4sUxW8v2Ikb8EOMVm0o7zAYhWRGq7rur0=,tag:UgXpXxwxFqLajWXz0zt8Pg==,type:str]
    #ENC[AES256_GCM,data:dJlx9h/gWyxSF2GTx0JF/Kh3WNd1yzNK9jkD5SqHQ+6jXTIHHQQuhdVBs6KbgMBetsNIjqaCYeU/+s5NCkWl,iv:fRx0Rimho6EcAI9tOp8j9cRQyB52/e5Mfjoreo5iAqs=,tag:bDobhesDu5sQTwTUE4E3IA==,type:comment]
    SECRET_RESTIC_REPOSITORY_S3: ENC[AES256_GCM,data:gLxgF//fq9T1A1Px2lgucosf7v1g0uHi,iv:1lYqbFQKRrIekMdAOuOXa2ee6taWokJIGmEHOh/FZMg=,tag:4pqxXg24XP12vwgTIoa++A==,type:str]
    SECRET_RESTIC_FAMILY_PV_REPO: ENC[AES256_GCM,data:bQohaKPs8YTgSHXHbcs1n4N1BRjpHYYsf5nYi5GjO/5Po6h9,iv:hK+pUw+wCwMj7xegbNwrncA6TxkhO4UqZbUU1sEE5yU=,tag:hRis0TdYlPLRdu+h6tbDPA==,type:str]
    SECRET_RESTIC_FAMILY_MEDIA_REPO: ENC[AES256_GCM,data:o2iRagpAwYZEy0IzVwOIRWI+2xwFiuSz,iv:SflB8Y6Tl73jHofkpwRy8gzj9VJfi4H4qLDFKFcZCBg=,tag:AqAxgIqK1Uhw/U573T4nuw==,type:str]
    SECRET_RESTIC_DEV_PV_REPO: ENC[AES256_GCM,data:49H985ALxTHfJ4mv3CGBcgEjbPCHVsz+,iv:kXoY38JjdBIfueJ4nQMh3ARnuBvubpWa6gdBM1M5/+Q=,tag:kqV1HlMTO+kvAxlWUAeFkQ==,type:str]
    SECRET_RESTIC_DEV_MEDIA_REPO: ENC[AES256_GCM,data:k3zWPC6JWkPzHbyOO9AUsa5Ec1ZWhC8d,iv:TRHDbP/cdIQrM/EvFhH+6Yu0IgYuCDXciIcXi9iWT24=,tag:C+pm9YiVIi6YBweBdY9OYA==,type:str]
    SECRET_RESTIC_BANG_PV_REPO: ENC[AES256_GCM,data:GFJT33KhQJh6h+8gRiAGEPw1cZdoFnRvXjQW7cFQNUo91FcT,iv:Cf6zfwG6CNlMMf9GoHXvpFo382bLSOtOS8rs4Xvr/7k=,tag:3gmLkuXSNyBzGGWrOy343w==,type:str]
    SECRET_RESTIC_BANG_MEDIA_REPO: ENC[AES256_GCM,data:WbG2dmJqSQqmNKySZFC+qFGPyT9nGPuJQVHCBwQvwIUnF1ET,iv:QzB2eQ6y5gLKHX5XdjAPkzXqvuoPqUald0PezMFadig=,tag:UXEJZnrnzNiWgf81huHkeA==,type:str]
    SECRET_RESTIC_BANG_BUF_REPO: ENC[AES256_GCM,data:ivlsju3Y/X8TZ+Xje+O1U1ZGY0qQzwMU2rckgfuVdPk38DWP,iv:SAWzzvYzTVmByNPKNS6cwcV+bVoGiDbz3kXpDlMsmZA=,tag:7iXZqz1RXmhhNbKRPAJKjQ==,type:str]
    SECRET_RESTIC_BANG_COVER_REPO: ENC[AES256_GCM,data:YRcNBwEkFXFpQlTioVS5rztvX26AaqCZg9kKscdeA9YhZs42,iv:i8KbflBkcA8X+tEclIlGZZ+4nmlBBR/ddrERVTXjSoI=,tag:qHzkdTOYYN0P5GDikAIChA==,type:str]
    SECRET_RESTIC_BANG_CLIP_REPO: ENC[AES256_GCM,data:xaRkq9DszGWrScsKXSapoBnkWaI0eXRndaIlEFgV8ZB0WrL9,iv:MpYW64JUH71tC2+yAXXWlg2NJLRJw1qburneCnA9Lqc=,tag:iyx+D2LU7jkDh57g6qSMSg==,type:str]
    SECRET_RESTIC_BANG_SRC_REPO: ENC[AES256_GCM,data:qzHeumZ411+qVGPyHok0AFb1fMvQ1ZoqprrRTDRxb+q882z0,iv:oTGpKEO6fhOIGpcFMjp+StNTfoNrHYnqbtA9c6Pf8tE=,tag:ajjwg+3xaenYLewsz0nixQ==,type:str]
    #ENC[AES256_GCM,data:mzTX5Eb5MwmP0wJ4EI/7F8NxFafjjKtFf9DhvzHKx/U2ZHJ42IfMD1NxWr6P,iv:kHPqh7gVl00sBMLwutp6fhI2kEAsQvYUnrJPZ4npo1A=,tag:usAxEbugCHoQDg/ImPU++g==,type:comment]
    #ENC[AES256_GCM,data:fRQD8rXzGv5oz25n24F+u28jX9gFm8ll8EkKnRzwksdAmJC9SSj8rMpz2dU=,iv:TmIRbXlM0nB7J7pm5kGXYb1DxOsPXc8O52QK/TfPYQY=,tag:y3Gnhfg+EzzeQTn2LydUaw==,type:comment]
    NTFY_EVE_TOKEN: ENC[AES256_GCM,data:KHjHg19fl2W7/N8RpVgnovI+5fyGU8mkFCsZc6JQCJ4=,iv:HuawtL2GVtEytMmu8pMQCcStYkzEyYDkWYtsFe5veIw=,tag:Csm16IoBwhAuI5p0FTFk9w==,type:str]
    NTFY_BOT_TOKEN: ENC[AES256_GCM,data:87yGN+Zvq+fNYn2RB0gcvAu7fQdCqZTEWQ+PlzlzdyI=,iv:axzlVnFwESI9cUEWG6njjKV4jeF0F+c+VBbnKVoejqs=,tag:nDV5FjN+0U43msXmAy5W+w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qh3gh9vltq82hgjxdtga37svmdvzj2zgdxzt0zzsh4rndmtlkujsmrw26m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjV0wwR2RYZ1RvR04rSzFW
            bWtrVGxGT0NNZWIzSXl3anQxSk92WWxKUGdBCmtDMmhZV0xHUS9sd2MxMWhrK2hy
            dkU3cDBvT1BLdGxrUXFtaWhCLzBQV1UKLS0tIGdkMjZsQjJxQzFyRlk1YkxUWmNX
            QlF0cC8wT25xdzB2NzRXYzVSYWIrc1UKhcw6w4z3sdKRAf+azZF17lz/cdKCbCOL
            76GZGbwYsphnjnn2DW75HQhKLLTCRHt4y7mb9Yfcy1hV6qFlyuEZJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-18T06:38:06Z"
    mac: ENC[AES256_GCM,data:EVbbL3B/iZkqQU/NoyOpXowfznSglezTFX1svkq81eOAueqV69+k2bppRvyy80bgxav948EDdWDOwZzy7+6M5aKomsBfqE89w4cLba5osz8uFhaIBt/PrNyFf/lA3CAYbEo+opYB1kD0KyOXp8UsTRSgcZfbEEepIv174v97Oho=,iv:fB+eNym6sVm82KgaqnKRHrHWATFWSrrnGshCcJPRfxQ=,tag:Vv035E2ynxrhLjp5SxvphA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
