---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &sec-name mod-auth
  namespace: flux-system
spec:
  secretStoreRef:
    name: vault-kv-backend
    kind: SecretStore
  target:
    name: *sec-name
    creationPolicy: Owner
    template:
      engineVersion: v2
      # htpasswd -bnBC 10 "" ${PWD} | tr -d ':\n' | base64 -w 0
      data:
        GRAFANA_OAUTH_CLIENT_ID: "{{ .GRAFANA_OAUTH_CLIENT_ID }}"
        GRAFANA_OAUTH_CLIENT_SECRET: "{{ .GRAFANA_OAUTH_CLIENT_SECRET }}"
        VIKUNJA_OAUTH_CLIENT_SECRET: "{{ .VIKUNJA_OAUTH_CLIENT }}"
        GITEA_OAUTH_CLIENT_SECRET: "{{ .GITEA_OAUTH_CLIENT }}"
        VAULT_OAUTH_CLIENT_SECRET: "{{ .VAULT_OAUTH_CLIENT }}"
        IMMICH_OAUTH_CLIENT_SECRET: "{{ .IMMICH_OAUTH_CLIENT }}"
        JELLYFIN_OAUTH_CLIENT_SECRET: "{{ .JELLYFIN_OAUTH_CLIENT }}"
        SHARE_SUBNET_CIDR: "{{ .SHARE_SUBNET_CIDR }}"
        AUTHELIA_JWT_SECRET: "{{ .AUTHELIA_JWT_SECRET }}"
        AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD: "{{ .AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD }}"
        AUTHELIA_SESSION_SECRET: "{{ .AUTHELIA_SESSION_SECRET }}"
        AUTHELIA_STORAGE_ENCRYPTION_KEY: "{{ .AUTHELIA_STORAGE_ENCRYPTION_KEY }}"
        AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET: "{{ .AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET }}"
        AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY: "{{ .AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY }}"
        SMTP_ACCOUNT_AUTH_EMAIL: "{{ .SMTP_ACCOUNT_AUTH_EMAIL }}"
        SMTP_ACCOUNT_AUTH_PWD: "{{ .SMTP_ACCOUNT_AUTH_PWD }}"
        SMTP_HOST: "{{ .SMTP_HOST }}"
        SECRET_DOMAIN: "{{ .SECRET_DOMAIN }}"
  dataFrom:
    - extract:
        key: monitor/grafana
    - extract:
        key: warez/vikunja
    - extract:
        key: dev/gitea
    - extract:
        key: secret/secret/vault
    - extract:
        key: media/jellyfin
    - extract:
        key: media/immich
    - extract:
        key: net/lan
    - extract:
        key: auth/authelia
    - extract:
        key: net/email
    - extract:
        key: net/inet
