apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cluster-settings.yaml
  - ./cluster-settings-user.yaml
  - ./cluster-secrets.sops.yaml
  - ./cluster-secrets-email.sops.yaml
  - ./cluster-secrets-user.sops.yaml
  - ./cluster-secrets-hw.sops.yaml
  - ./externalsecret.yaml
