apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:mQjhduZnRjAvFVjlDuAXxe1GNn4B+/dw3vygcHvkEh0Yzcy2,iv:xQ4d34gAjSxqlPH6pAVqJ5FnfgaRAs2+l9bKll30IfU=,tag:3sFMfbfRNydNKT/3sBMrMQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:WO5tBAitRAhYhfc2HQZ6SiNeDtxsGgAiOcqZAMTlh08ZUQ7FS7NEEN1cZoFGYmSouz03Int3MM28X0TObTTPxwnrbos6uPQkjN0HAXlkaUvK5u/rf/itb1HHMo6sL74SN87yK4JMYurQnAp1Yytjo7NaVkSwVmtYesl2Dg2J5SptmhnmmwLLAK/VR5c19uuGU24CiIJmNX3wJNAkn5v043xSd5ZjcuVy5Te569N8lQ==,iv:51OcRO40wNdMp6EQnAOCwezEUOvM58aYNddydCy4WBk=,tag:+XfSwGBKRQrFIDlP0lvlhw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qh3gh9vltq82hgjxdtga37svmdvzj2zgdxzt0zzsh4rndmtlkujsmrw26m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvQUw1dDZCRDQvZmNvSWd1
            SWEzNERJOFp1MEszVDI4bVpuZ3I0enBXQVZBClcyTmtjU1RtR1VEZ3ZxNVk0dTNL
            c0tuM0RrblR4ZDJIS0ZRV0VueXUzeXMKLS0tIFZkQ2hhTy9pZlA1ckhHTzdHNDNi
            ZnhyOEQzWllHa1FRSUgxVzM1SzMwRGsKG2RNu6Ekt1N7BkfMt87B5ohrXmxzPIcc
            Roqjl26rfRCE/ZSQKFAu+YJXIBSP/4NGpAcc0bhNa6Cvy5DWCKub9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-15T01:07:38Z"
    mac: ENC[AES256_GCM,data:bOO3ISwprqumbW+ben357qWDQvUsw4428IyfIIgQVDc8SGQUWtMIxEyeuePS2ZD6MtN+QOjSBV2SyBswIb8Le1rwjMu2jpDkIlWFRcP0XVFmwaUHMaPlClgZLHGXw1HyBbINjuJ7CGrRASsZhkoGoNQvRlufT5dhKaWQQDzAOCo=,iv:1eIWiTU3hWxu5bv7Q9iuNpW8xuQ/MeA5f8xGrQJNGgk=,tag:kpJ8LJkE3+4+G4rkkxtf2Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
